import Head from "next/head";
import Layout from "@/components/layout/layout";
import OurAim from "@/components/ourAimLayout/ourAimLayout";
import LandingLayout from "@/components/landingLayout/landingLayout";
import GetStarted from "@/components/getStartedLayout/getStartedlayout";
import HelpPreview from "@/helpParentLayout/helpPreviewLayout/helpPreviewLayout";
import AboutUsPreview from "@/components/aboutUsPreviewLayout/aboutUsPreviewLayout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>ProCv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingLayout />
      <AboutUsPreview />
      <OurAim />
      <GetStarted />
      <HelpPreview />
    </Layout>
  );
}

// https://demo.templatemonster.com/demo/81610.html?_gl=1*1o3llx5*_ga*MTkxNzY4OTMzMS4xNjkxOTIyODMz*_ga_FTPYEGT5LY*MTY5MTkyMjgzMy4xLjEuMTY5MTkyNDU2Ni41Mi4wLjA.&_ga=2.242260101.609858189.1691922835-1917689331.1691922833
// For Logo: https://looka.com/

// Problem in getInTouch
